package de.teccheck.logiledmod;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import org.lwjgl.input.Keyboard;

import com.logitech.gaming.LogiLED;

import de.teccheck.logiledmod.config.Configs;
import net.minecraft.client.Minecraft;
import net.minecraft.client.settings.GameSettings;
import net.minecraft.client.settings.KeyBinding;
import net.minecraft.util.EnumChatFormatting;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

@Mod(modid = LogiLEDMod.MODID, name = LogiLEDMod.NAME, version = LogiLEDMod.VERSION, guiFactory = LogiLEDMod.GUI_FACTORY, clientSideOnly = LogiLEDMod.CLIENT_SIDE_ONLY, acceptedMinecraftVersions = LogiLEDMod.MC_VERSIONS, useMetadata = LogiLEDMod.USE_METADATA)
public class LogiLEDMod {
	public static final String GUI_FACTORY = "de.teccheck." + LogiLEDMod.MODID + ".config.ConfigGuiFactory";
	public static final String MODID = "logiledmod";
	public static final String VERSION = "0.5";
	public static final String NAME = "Logitech LED Mod";
	public static final String MC_VERSIONS = "";
	public static final boolean CLIENT_SIDE_ONLY = true;
	public static final boolean USE_METADATA = true;

	public static File configFile = null;

	@EventHandler
	public void preInit(FMLPreInitializationEvent event) {
		// Setup for Mod Infos
		ModMetadata data = event.getModMetadata();
		data.autogenerated = false;
		data.version = VERSION;
		data.modId = MODID;
		data.name = EnumChatFormatting.AQUA + "Logitech" + EnumChatFormatting.RESET + " " + EnumChatFormatting.RED + "L"
				+ EnumChatFormatting.GREEN + "E" + EnumChatFormatting.BLUE + "D" + EnumChatFormatting.AQUA + " Mod";
		data.description = "A mod that adds support for" + EnumChatFormatting.AQUA + " Logitech G"
				+ EnumChatFormatting.RESET + " Keyboard Lighting \nMade with the Logitech LED Illumination SDK\nLink: https://www.logitechg.com/en-us/innovation/developer-lab.html";
		data.credits = "TeckCheck";
		data.url = "https://github.com/TecCheck/LogitechLedMod";

		// Setup for Mod Configs
		configFile = event.getSuggestedConfigurationFile();
		Configs.LoadConfigSettings(configFile);
		Configs.applyConfigs();
	}

	@EventHandler
	public void init(FMLInitializationEvent event) {
		// Registering Events
		MinecraftForge.EVENT_BUS.register(new Events());
		FMLCommonHandler.instance().bus().register(new Events());

	}

	@EventHandler
	public void postInit(FMLPostInitializationEvent event) {
		// Post Init empty
	}
}